# Generated by Django 5.1.3 on 2024-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0006_alter_empresa_email_alter_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocao',
            unique_together={('nome_produto', 'categoria', 'data_inicio', 'data_termino')},
        ),
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ELETRONICO', 'Eletrônico'), ('ROUPA', 'Roupa'), ('ALIMENTO', 'Alimento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='disponibilidade',
        ),
    ]
