# Generated by Django 5.1.3 on 2024-12-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0008_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='promocao',
            name='loja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(default='Endereço Padrão', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(default='Nome da Empresa', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(default='Categoria Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateField(default='2024-08-01'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_termino',
            field=models.DateTimeField(default='2024-08-01'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(default='Descrição Padrão'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='nome_produto',
            field=models.CharField(default='Produto Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='preco_original',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
