# Generated by Django 5.1.3 on 2024-12-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0009_delete_produto_promocao_loja_alter_empresa_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_termino',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='nome_produto',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='loja',
        ),
    ]
