# Generated by Django 5.1.3 on 2024-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0010_alter_promocao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
