# Generated by Django 5.1.3 on 2024-12-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0011_promocao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='descricao',
        ),
    ]
